language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn install
  - yarn build
  - npm run travis-build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master